#cloud-config
autoinstall:
  # version is an Autoinstall required field.
  version: 1

  # User creation can occur in one of 3 ways:
  # 1. Create a user using this `identity` section.
  # 2. Create users as documented in cloud-init inside the user-data section,
  #    which means this single-user identity section may be removed.
  # 3. Prompt for user configuration on first boot.  Remove this identity
  #    section and see the "Installation without a default user" section.
  identity:
    realname: ''
    username: ubuntu
    # A password hash is needed. `mkpasswd --method=SHA-512` can help.
    # mkpasswd can be found in the package 'whois'
    # a123
    password: '$6$eYdBgznmdMy1zOFS$9RoOLmolIkLQVUuOGzB7OkYFxevJqhPB.8h5IxS6dCvWTYqfbmEAcMi7soWxDH4FczfcrLTS3FdpgY39gI8ql1'
    hostname: ubuntu-desktop

  late-commands:
     - curtin in-target -- apt-get -y install gnome-shell-extension-manager gnome-shell-extensions gnome-tweaks python3 python3-serial python3-pyudev python3-evdev
     - wget https://raw.githubusercontent.com/imrisaac/ubuntu_yaml_autoinstall_test/refs/heads/master/post-install.sh -P /target/root/
     - curtin in-target -- chmod +x /root/post-install.sh
     - curtin in-target -- bash /root/post-install.sh
     - curtin in-target -- rm /root/post-install.sh
